Ya disk handler
ProgiFrogi/TGDesignBot pull request #1
Opened 2024-03-24 14:22 UTC by KiriProg

2024-03-25 10:29 UTC, MRedor requested changes

2024-03-25 10:29 UTC, MRedor commented on YaDiskHandle/YaDiskHandler.py
> +#            'path' - the path of file from root to last directory.
Ого
А почему мы их делаем словарями?

Давай вынесем в классы – так будет сильно удобнее в разработке, а то сейчас все сильно завязано на ключевые слова

2024-03-25 10:29 UTC, MRedor commented on YaDiskHandle/YaDiskHandler.py
> +        raise Exception("Invalid token")
Такие проверки лучше выносить в отдельные функции
Они нужны будут в каждом методе хендлера

2024-03-25 10:29 UTC, MRedor commented on YaDiskHandle/YaDiskHandler.py
> +        if item.is_dir() and not ('фото' in item.name.lower() or "photo" in item.name.lower()):
проверку в отдельную функцию с понятным именем

2024-03-25 10:29 UTC, MRedor commented on YaDiskHandle/YaDiskHandler.py
> +        if item.is_dir and ('фото' in item.name.lower() or "photo" in item.name.lower()):
проверку в отдельную функцию с понятным именем

2024-03-25 10:29 UTC, MRedor commented on YaDiskHandle/YaDiskHandler.py
> +            if item.name.endswith('.pptx'):
проверку в отдельную функцию с понятным именем

2024-03-25 10:29 UTC, MRedor commented on YaDiskHandle/YaDiskHandler.py
> +            elif item.name.endswith('.zip'):
проверку в отдельную функцию с понятным именем

2024-03-25 10:29 UTC, MRedor commented on YaDiskHandle/YaDiskHandler.py
> +                fonts.append({'file': item.file,
В зипе могут быть не только шрифты, а мало ли что еще
Зато папка со шрифтами обычно так и называется

2024-03-25 11:38 UTC, KiriProg commented on YaDiskHandle/YaDiskHandler.py
> +#            'path' - the path of file from root to last directory.
Я не умею в ООП на питоне =(
Ну если прям надо, то можно....
А вообще словарь - это хешмапа на сколько я знаю. Поэтому работает быстро достаточно

2024-04-16 13:14 UTC, MRedor approved these changes
Добавить комменты к функциям и можно мержить

Остальное – на подумать

2024-04-16 13:14 UTC, MRedor commented on YaDiskHandle/YaDiskHandler.py
> +
Давай добавим здесь комментарий, что за токен, как его получить, где его хранить

2024-04-16 13:14 UTC, MRedor commented on YaDiskHandle/YaDiskHandler.py
> +def is_images(item) -> bool:
давай добавим варианты: графика/graphics, изображения/images – и там, и там можно проверять по корню слова

2024-04-16 13:14 UTC, MRedor commented on YaDiskHandle/Tree.py
> +    def __search__(self, node: Node, target: str, lst: list):
А в какой ситуации у нас получается, что таргетных нод больше одной?

2024-04-16 13:14 UTC, MRedor commented on YaDiskHandle/Tree.py
> +    def __get_parent__(self, node: Node, target: str, lst: list):
Нужен коммент, что делает функция и что просит в параметрах

2024-04-16 13:14 UTC, MRedor commented on YaDiskHandle/Tree.py
> +    def exist(self, name: str) -> bool:
Нужен коммент, что делает функция

2024-04-16 13:14 UTC, MRedor commented on YaDiskHandle/Tree.py
> +class Tree:
Я не очень понимаю, почему мы для любого запроса сообщаем имя ноды, а потом ее ищем
Вместо того, чтобы сразу передавать саму ноду

В любом случае, можно так оставить, но точно ли это самый удобный способ?

2024-04-16 14:43 UTC, KiriProg commented on YaDiskHandle/Tree.py
> +    def __search__(self, node: Node, target: str, lst: list):
Никогда. Это небольшой костыль, чтобы получить именно ссылку на таргет ноду

2024-04-16 14:46 UTC, KiriProg commented on YaDiskHandle/Tree.py
> +class Tree:
Ну дерево - это схема папок. Поэтому ноды мы ищем по имени папки. Артём работает с таким деревом и ему удобно(ну он не жаловался пока)))

2024-04-16 16:01 UTC, MRedor commented on YaDiskHandle/Tree.py
> +    def __search__(self, node: Node, target: str, lst: list):
Ааа, блин, я поняла
Я подумаю, как это сделать более красиво – оставь пока коммент про это плиз

2024-07-27 08:56 UTC, closed without merging