Pptx handler
ProgiFrogi/TGDesignBot pull request #2
Opened 2024-03-24 14:25 UTC by KiriProg

2024-03-25 10:18 UTC, MRedor requested changes

2024-03-25 10:18 UTC, MRedor commented on pptxHandler/pptxHandler.py
> +def install_templates(path: str, templates: list):
Где-то потерялось объявление класса template

2024-03-25 10:18 UTC, MRedor commented on pptxHandler/pptxHandler.py
> +        os.makedirs(path, exist_ok=True)
Выглядит как двойная проверка

2024-03-25 10:18 UTC, MRedor commented on pptxHandler/pptxHandler.py
> +        raise Exception("Can't install templates")
Без контекста использования функции не понятно, почему мы делаем именно так – если с каким-то файлом не получилось, то сбрасываем все
Это еще и в плохую сторону может сыграть – если у нас была старая версия файла, мы ее так удалим случайно

Но даже если оставляем так, хорошо бы прокинуть причину, почему не смогли установить

2024-03-25 10:18 UTC, MRedor commented on pptxHandler/pptxHandler.py
> +        raise Exception("No such file or directory")
Предлагаю вынести в отдельную функцию, чтобы потом не дублировать

(+ имеет смысл и в remove_all_comments использовать)

2024-03-25 10:18 UTC, MRedor commented on pptxHandler/pptxHandler.py
> +                slides_info.append({'slide_id': comment.slide.slide_number - 1,
Зачем нам это -1?

2024-03-25 10:18 UTC, MRedor commented on pptxHandler/pptxHandler.py
> +                                   'tags': comment.text})
Надо всякие пробельные символы удалить еще в какой-то момент

2024-03-25 10:18 UTC, MRedor commented on pptxHandler/pptxHandler.py
Здесь можно сразу добавить фильтр слайдов по тегу и склейку нового pptx файла из них
Можно и не сразу, в целом)

2024-03-25 11:42 UTC, KiriProg commented on pptxHandler/pptxHandler.py
> +                slides_info.append({'slide_id': comment.slide.slide_number - 1,
для 0 - индексации. Доступ к слайдам по [] в шаблоне реализован для 0 - индексации. А slide_number возвращет номера с 1

2024-03-25 11:43 UTC, KiriProg commented on pptxHandler/pptxHandler.py
> +                                   'tags': comment.text})
это всё делается через split(';') (или другой символ - сепаратор для разделения тегов).  А птом удалить пробелы не проблема.

2024-03-25 11:44 UTC, KiriProg commented on pptxHandler/pptxHandler.py
Не очень понял. Функция, которая достаёт слайд и возвращает презентацию будет обязательно. Склейку тоже реализую

2024-04-16 13:25 UTC, MRedor approved these changes
Выглядит хорошо – можно мержить

Тестировал на больших файлах? Если нет, лучше посмотреть руками немного: проставить теги, посмотреть что будет, если по запросу ничего не найдется или как долго будет работать в общем случае

2024-04-16 13:25 UTC, MRedor commented on pptxHandler/pptxHandler.py
> +def check_directory(path: str):
можно назвать exists – так в месте вызова сразу будет понятно, что проверяется

2024-04-16 13:25 UTC, MRedor commented on pptxHandler/pptxHandler.py
> +        presentation.save(path, slides.export.SaveFormat.PPTX)
Здесь можно удалить пустые строки

Функция маленькая – читаться будет норм

2024-04-16 13:25 UTC, MRedor commented on pptxHandler/pptxHandler.py
> +
А вот здесь очень хочется убрать пустую строку

2024-04-16 13:25 UTC, MRedor commented on pptxHandler/pptxHandler.py
> +def remove_all_watermarks(path: str):
👍

2024-07-27 08:56 UTC, closed without merging